Add SD and RasberryPi exports

diff --git a/experimental/files/scripts/fct_export b/experimental/files/scripts/fct_export
--- a/experimental/files/scripts/fct_export
+++ b/experimental/files/scripts/fct_export
@@ -5,20 +5,19 @@ source $FUNCDIR/fct_vars
 
 create_image() {
     # Delete old image delete emulator
-    echo -ne "[${INFO} 1/4 ${NORL}] Build rootfs image ...                      "
+    echo -ne "[${INFO} 1/4 ${NORL}] Build rootfs image ...                                    "
     mkdir -p $IMAGESDIR
     rm -f $ROOTFSIMG 2>/dev/null
-    [ "$ARCH" = "arm" ] && rm $ROOTFSDIR/usr/bin/qemu-arm-static 2>/dev/null
 
-    # Clean apt sources before create image
+    # Clean image before creation
     SOURCES=`cat $ROOTFSDIR/etc/apt/sources.list`
     echo "# $SOURCES" > $ROOTFSDIR/etc/apt/sources.list
     $CHROOT $ROOTFSDIR /bin/bash -c "apt-get update" &>/dev/null
     echo "$SOURCES"   > $ROOTFSDIR/etc/apt/sources.list
+    [ "$ARCH" = "arm" ] && rm $ROOTFSDIR/usr/bin/qemu-arm-static 2>/dev/null
 
     # Create raw image and copy files
-    if
-    dd if=/dev/zero of=$ROOTFSIMG bs=1024 count=1500000 &>/dev/null; then
+    if dd if=/dev/zero of=$ROOTFSIMG bs=1024 count=1500000 &>/dev/null; then
         # Format and copy data
 	if mkfs.ext2 -F $ROOTFSIMG >/dev/null >/dev/null 2>/dev/null && mount -o loop $ROOTFSIMG $MOUNTDIR 2>/dev/null; then
             echo -ne "(${DONE}make${NORL}) "
@@ -40,27 +39,99 @@ create_image() {
     fi
 }
 
+prepare_sd() {
+    # Umount all partitions and copy RasberryPi files
+    DEVICE=$1; DRIVE_PARTS=`blkid -o device | grep $DEVICE`
+    for part in $DRIVE_PARTS; do
+        umount $part 2>/dev/null
+    done
+
+    # Clean drive and creating partitions
+    echo -ne "[${INFO} 2/4 ${NORL}] Creating new partitions ...                               "
+    parted -s /dev/$DEVICE mktable msdos                &>/dev/null   # Clean drive
+    parted -s /dev/$DEVICE mkpart primary fat16 0 2048M &>/dev/null   # Create partition 2G
+    parted -s /dev/$DEVICE set 1 boot on                &>/dev/null   # Change partition type
+    sleep 2                                                           # Time to update partition database
+    if test -e /dev/$DEVICE"1"; then
+        echo -e "(${DONE}done${NORL})"
+    else
+        echo -e "(${ERRO}failed${NORL})" && exit 1
+    fi
+
+    # Format new partition
+    echo -ne "[${INFO} 3/4 ${NORL}] Formatting device ...                                     "
+    if mkfs.msdos -I -n "oddistro" -F 16 /dev/$DEVICE"1" &>/dev/null; then
+        echo -e "(${DONE}done${NORL})"
+    else
+        echo -e "(${ERRO}failed${NORL})" && exit 1
+    fi
+}
+
+export_to_sd() {
+    # Create partition and filesystems SD
+    prepare_sd $1
+    DEVICE=$1"1"
+
+    # Mount drive, prepare target and copy files to SD
+    cp -r $ISOFILES/* $TARGETDIR/
+    echo "DEFAULT $KERNELIMG initrd=$INITRDIMG rw quiet loglevel=0 aufs=yes bootdev=/dev/sda1" > $TARGETDIR/syslinux.cfg
+    mount /dev/$DEVICE $MOUNTDIR
+
+    # Mount device and copy files
+    echo -ne "[${INFO} 4/4 ${NORL}] Copy opendomo files ...                                   "
+    if cp -r $TARGETDIR/* $MOUNTDIR/; then
+        echo -e "(${DONE}done${NORL})"
+    else
+        sleep 5 & umount /dev/$DEVICE
+        echo -e "(${ERRO}failed${NORL})" && exit 1
+    fi
+
+    # Installing syslinux
+    syslinux -i /dev/$DEVICE
+    sleep 5 & umount /dev/$DEVICE
+}
+
+export_to_rpi() {
+    # Create partition and filesystems SD
+    prepare_sd $1
+    DEVICE=$1"1"
+
+    # Mount drive, prepare target and copy files to SD
+    cp -r $RPIFILES/* $TARGETDIR/
+    mount /dev/$DEVICE $MOUNTDIR || exit 1
+
+    echo -ne "[${INFO} 4/4 ${NORL}] Copy opendomo files ...                                   "
+    if cp -r $TARGETDIR/* $MOUNTDIR/; then
+        sleep 5
+        umount /dev/$DEVICE
+        echo -e "(${DONE}done${NORL})"
+    else
+        sleep 5
+        umount /dev/$DEVICE
+        echo -e "(${ERRO}failed${NORL})" && exit 1
+    fi
+}
+
 export_to_vmdk() {
     # Delete old images and copy isofiles
     rm $EXPORTDIR/$NAME.img $EXPORTDIR/$INAME.vmdk 2>/dev/null
     cp -r $ISOFILES/* $TARGETDIR/
 
-    # Creating syslinx file
+    # Creating syslinux file
     echo "DEFAULT $KERNELIMG initrd=$INITRDIMG rw quiet loglevel=0 aufs=yes bootdev=/dev/sda" > $TARGETDIR/syslinux.cfg
 
-    # Creating loodev
-    echo -ne "[${INFO} 2/4 ${NORL}] Creating raw image ...                      "
+    # Creating loopdev
+    echo -ne "[${INFO} 2/4 ${NORL}] Creating raw image ...                                    "
     if qemu-img create -f raw $EXPORTDIR/$INAME.img 2G &>/dev/null; then
         losetup -f $EXPORTDIR/$INAME.img
         LOOPDEV=`losetup -a | grep -m1 "opendomo" | cut -f1 -d: | tail -n1`
         echo -e "(${DONE}done${NORL})"
     else
-        echo -e "(${ERRO}failed${NORL})"
-        exit 1
+        echo -e "(${ERRO}failed${NORL})" && exit 1
     fi
 
     # Format, mount and copy files
-    echo -ne "[${INFO} 3/4 ${NORL}] Formatting raw image ...                    "
+    echo -ne "[${INFO} 3/4 ${NORL}] Formatting raw image ...                                  "
     if mkfs.vfat -n oddistro $LOOPDEV &>/dev/null; then
         mount $EXPORTDIR/$INAME.img $MOUNTDIR
         cp -r $TARGETDIR/* $MOUNTDIR/
@@ -79,25 +150,15 @@ export_to_vmdk() {
         done
         echo -e "(${DONE}done${NORL})"
     else
-        echo -e "(${ERRO}failed${NORL})"
+        echo -e "(${ERRO}failed${NORL})"  && exit 1
     fi
 
     # Convert raw to vmdk
-    echo -ne "[${INFO} 4/4 ${NORL}] Converting raw to vmdk image ...            "
+    echo -ne "[${INFO} 4/4 ${NORL}] Converting raw to vmdk image ...                          "
     if qemu-img convert -O vmdk $EXPORTDIR/$INAME.img $EXPORTDIR/$INAME.vmdk; then
         chown `users | cut -f1 -d" "` $EXPORTDIR/$INAME.*
         echo -e "(${DONE}done${NORL})"
     else
-        echo -e "(${ERRO}failed${NORL})"
+        echo -e "(${ERRO}failed${NORL})"  && exit 1
     fi
-}
-
-export_to_sd() {
-    #TODO
-    echo -ne "[${INFO} 1/1 ${NORL}] Exporting to SD ...                         "
-}
-
-export_to_rpi() {
-    echo -ne "[${INFO} 1/1 ${NORL}] Exporting to RPI ...                        "
-    #TODO
 }
diff --git a/experimental/files/scripts/fct_main b/experimental/files/scripts/fct_main
--- a/experimental/files/scripts/fct_main
+++ b/experimental/files/scripts/fct_main
@@ -4,14 +4,12 @@ FUNCDIR=files/scripts/
 source $FUNCDIR/fct_vars
 source $FUNCDIR/fct_build
 source $FUNCDIR/fct_export
-mkdir -p $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
-chown `users | cut -f1 -d" "` $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
 
 case $1 in
     clean )
         echo -e "########## Cleaning OpenDomoOS SDK ##########"
         echo
-        echo -ne "[${INFO} 1/1 ${NORL}] Cleaning SDK ...                             "
+        echo -ne "[${INFO} 1/1 ${NORL}] Cleaning SDK ...                                          "
         if rm -r $TEMPDIR/* &>/dev/null; then
             echo -e "(${DONE}done${NORL})"
         else
@@ -21,36 +19,99 @@ case $1 in
         echo
     ;;
     build )
+        # Previous checks before build
+        if test -z $2; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select a valid arch [ i386 or arm ]"      & exit 1
+        elif [ "$2" != "arm" ] && [ "$2" != "i386" ]; then
+            echo -e "[${ERRO}ERROR${NORL}] Selected arch is not valid [ i386 or arm ]"        & exit 1
+        elif [ "$2" = "arm" ] && ! test -x /usr/bin/qemu-arm-static; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install qemu-user-static build arm image" & exit 1
+        else
+            mkdir -p $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
+            chown `users | cut -f1 -d" "` $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
+        fi
+
         echo -e "########## Building OpenDomoOS packages for $2 ##########"
         echo
-        echo -ne "[${INFO} 1/5 ${NORL}] Downloading rootfs package ...              "
+        echo -ne "[${INFO} 1/5 ${NORL}] Downloading rootfs package ...                            "
         download_target
-        echo -ne "[${INFO} 2/5 ${NORL}] Extract rootfs package ...                  "
+        echo -ne "[${INFO} 2/5 ${NORL}] Extract rootfs package ...                                "
         extract_target
-        echo -ne "[${INFO} 3/5 ${NORL}] Build rootstrap image ...                   "
+        echo -ne "[${INFO} 3/5 ${NORL}] Build rootstrap image ...                                 "
         build_rootstrap
-        echo -ne "[${INFO} 4/5 ${NORL}] Creating opendomo packages ...              "
+        echo -ne "[${INFO} 4/5 ${NORL}] Creating opendomo package ...                             "
         create_packages
-        echo -ne "[${INFO} 5/5 ${NORL}] Install opendomo packages in rootfs ...     "
+        echo -ne "[${INFO} 5/5 ${NORL}] Install opendomo package in rootfs ...                    "
         install_packages
         echo
     ;;
     assemble )
+        # Previous checks before assemble
+        if test -z $2; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select a valid arch [ i386 or arm ]"      & exit 1
+        elif [ "$2" != "arm" ] && [ "$2" != "i386" ]; then
+            echo -e "[${ERRO}ERROR${NORL}] Selected arch is not valid [ i386 or arm ]"        & exit 1
+        elif [ "$2" = "arm" ] && ! test -x /usr/bin/qemu-arm-static; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install qemu-user-static build arm image" & exit 1
+        else
+            mkdir -p $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
+            chown `users | cut -f1 -d" "` $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
+        fi
+
         echo -e "########## Building OpenDomoOS for $2 ##########"
         echo
-        echo -ne "[${INFO} 1/3 ${NORL}] Downloading rootfs package ...              "
+        echo -ne "[${INFO} 1/3 ${NORL}] Downloading rootfs package ...                            "
         download_target
-        echo -ne "[${INFO} 2/3 ${NORL}] Extract rootfs package ...                  "
+        echo -ne "[${INFO} 2/3 ${NORL}] Extract rootfs package ...                                "
         extract_target
-        echo -ne "[${INFO} 3/3 ${NORL}] Install opendomo packages in rootfs ...     "
         install_packages
         echo
     ;;
     export )
-        echo -e "########## Exporting OpenDomoOS to $2 ##########"
+        # Previous checks before export
+        if test -z $2; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select a valid export [ vmdk, sd or rpi ]" & exit 1
+        elif [ "$2" != "sd" ] && [ "$2" != "vmdk" ] && [ "$2" != "rpi" ]; then
+            echo -e "[${ERRO}ERROR${NORL}] Selected option is not valid [ vmdk, sd or rpi ]"   & exit 1
+        elif [ "$2" = "rpi" ] && test -z $3; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select disk to export [ sda, sdb, sdc ]"   & exit 1
+        elif [ "$2" = "rpi" ] && ! test -x /sbin/parted; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install parted for sd export"              & exit 1
+        elif [ "$2" = "rpi" ] && ! test -x /usr/bin/qemu-arm-static; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install qemu-user-static for arm export"   & exit 1
+        elif [ "$2" = "rpi" ] && test `echo "${3: -1}"` -eq `echo "${3: -1}"` 2>/dev/null; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select disk to export no a partition"      & exit 1
+        elif [ "$2" = "rpi" ] && ! test -e /dev/$3; then
+            echo -e "[${ERRO}ERROR${NORL}] Selected device don't exist"                        & exit 1
+        elif [ "$2" = "vmdk" ] && ! test -x /usr/bin/qemu-img; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install qemu-utils for vmdk export"        & exit 1
+        elif [ "$2" = "vmdk" ] && ! test -x /usr/bin/extlinux; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install extlinux for vmdk export"          & exit 1
+        elif [ "$2" = "sd" ] && test -z $3; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select disk to export [ sda, sdb, sdc ]"   & exit 1
+        elif [ "$2" = "sd" ] && ! test -x /usr/bin/syslinux; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install syslinux for sd export"            & exit 1
+        elif [ "$2" = "sd" ] && ! test -x /sbin/parted; then
+            echo -e "[${ERRO}ERROR${NORL}] You need install parted for sd export"              & exit 1
+        elif [ "$2" = "sd" ] && test `echo "${3: -1}"` -eq `echo "${3: -1}"` 2>/dev/null; then
+            echo -e "[${ERRO}ERROR${NORL}] You need select disk to export no a partition"      & exit 1
+        elif [ "$2" = "sd" ] && ! test -b /dev/$3; then
+            echo -e "[${ERRO}ERROR${NORL}] Selected device don't exist"                        & exit 1
+        fi
+
+	echo -e "########## Exporting OpenDomoOS to $2 ##########"
         echo
+        if [ "$2" != "vmdk" ]; then
+            echo -ne "[${WARN} ask ${NORL}] This action delete all data in $3, are you sure? (y/n)   "
+            read -s -n1 ASK
+            if [ "$ASK" = "y" ]; then
+		echo -e "(${DONE}yes${NORL})"
+            else
+                echo -e "(${ERRO}no${NORL})" && exit 1
+            fi
+	fi
         create_image
-        export_to_$2
+        export_to_$2 $3
         echo
     ;;
 esac
